MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

# Custom events
# coins:
MOVED_TO_COIN = "MOVED_TO_COIN"
#MOVED_AWAY_FROM_COIN = "MOVED_AWAY_FROM_COIN"
# Crates:
CRATE_IN_POSSIBLE_EXPLOSION = "CRATE_IN_POSSIBLE_EXPLOSION"
BOMB_PLACED_NEXT_TO_CRATE = "BOMB_PLACED_NEXT_TO_CRATE"
# MOVED_TO_CRATE = "MOVED_TO_CRATE"
CRATE_DESTROYED_NOT_KILLED_SELF = "CRATE_DESTROYED_NOT_KILLED_SELF"
#MISSED_CRATE_OPPORTUNITY = "MISSED_CRATE_OPPORTUNITY"

# Safe/Danger events:
MOVED_ONTO_SAFE_TILE = "MOVED_ONTO_SAFE_TILE"
MOVED_INTO_DANGER = "MOVED_INTO_DANGER"
MOVED_INTO_EXPLOSION = "MOVED_INTO_EXPLOSION"
MOVED_TOWARDS_SAFE_TILE = "MOVED_TOWARDS_SAFE_TILE"
MOVED_AWAY_FROM_SAFE_TILE = "MOVED_AWAY_FROM_SAFE_TILE"
NO_MOVE_WHILE_ON_DANGER_TILE = "NO_MOVE_WHILE_ON_DANGER_TILE"
DID_NOT_CHOOSE_SAVING_MOVE = "DID_NOT_CHOOSE_SAVING_MOVE"

# Bomb related events:
BOMB_EXPLODED_AND_DIDNT_KILLED_SELF_YET = "BOMB_EXPLODED_AND_DIDNT_KILLED_SELF_YET"
SURVIVED_BOMB = "SURVIVED_BOMB"
CRATE_IN_POSSIBLE_EXPLOSION = "CRATE_IN_POSSIBLE_EXPLOSION"
DROPPED_BOMB_WITH_NO_CRATE_IN_RANGE = "DROPPED_BOMB_WITH_NO_CRATE_IN_RANGE"
BOMB_EXPLODED_BUT_DIDNT_DESTROYED_CRATE = "BOMB_EXPLODED_BUT_DIDNT_DESTROYED_CRATE" # crate cound wurde nicht gesenkt..
INVALID_BOMB_DROP = "INVALID_BOMB_DROP"
BOMB_DROPPED_WITH_NO_ESCAPE = "BOMB_DROPPED_WITH_NO_ESCAPE"

# Self-actions:
WALKING_IN_CIRCLES = "WALKING_IN_CIRCLES"
EXPLORED_NEW_TILE = "EXPLORED_NEW_TILE"
MOVED_AWAY_FROM_DEAD_END = "MOVED_AWAY_FROM_DEAD_END"

#enemys
GOT_KILLED_BY_OPPONENT = "GOT_KILLED_BY_OPPONENT"
